@startuml dragons
class Creature{
    - int pv
    - int pa
    - int niveau
    + {static} int cpt
    + void affiche()
    + int attaque()
    + void suibitDegat(int degat)
    + bool estVivant()
}

class Heros{
    - String nom
    - int pa
    - int pv
    + affiche()
    + attaque()
    + suibitDegat(int degat)
    + bool estVivant()
}
@enduml